### ISSUE TITLE
Role Scoper

### ISSUE THREAD

**Issue by honzamelena** [markoheijnen/wp-no-taxonomy-base#17]
Hi,

this plugin is awesome, it is small, does exacly what I want and is easy to use. But it does not work with Role Scoper. When both plugins are activated, I get 404 on every page (if I don't type the taxonomy base).

Maybe this will help you: Try downloading the wordpress seo by yoast, because there is one checkbox (under permalinks in his plugin section) and there you can strip "category" slug. And it works but I need it for custom taxonomies. Can you look into this problem? I would be very gratefull.

Thank you!

**Comment by markoheijnen** [comment]
I played with it but don't see the issue

**Comment by honzamelena** [comment]
Sorry to bother you, it seems that I have some problem with templatic theme or some other plugins. Thanks anyway!

**Comment by markoheijnen** [comment]
No problem. The cause of 404's can be tricky to find.
